import type { Metadata } from 'next'

export const siteConfig = {
  name: 'Dawan Africa',
  description: 'Uncovering the Continent Through Its Own Lens',
  url: process.env.NODE_ENV === 'production' ? 'https://dawan.africa' : 'http://localhost:3000',
  themeColor: '#2EC6FE',
}

export const sharedMetadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.name,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: [
    'Africa',
    'News',
    'Markets',
    'Finance',
    'Economics',
    'Business',
    'Investment',
    'Analysis',
    'Dawan Africa',
    'NTV Kenya',
    'Citizen TV',
    'KTN News',
    'K24 TV',
    'Inooro TV',
    'Kenya Television Network',
    'Kiss TV',
    'TV47 Kenya',
    'Y254 Television',
    'Shabelle TV',
    'Somalia National Television',
    'Goobjoog TV',
    'Horn Cable Television',
    'Universal Television',
    'Eastern Television Network',
    'Puntland TV',
    'Jubbaland TV',
    'Kalsann TV',
    'Dalka TV',
    'Somaliland National TV',
    'SLNTV',
    'Horn Observer',
    'SONNA',
    'EBC',
    'ETV News',
    'Fana Broadcasting',
    'ESAT',
    'Kana TV',
    'Walta TV',
    'OBN',
    'Oromia Broadcasting Network',
    'Tigrai TV',
    'Ahadu Television',
    'Nahoo TV',
    'JTV Ethiopia',
    'Amhara Media Corporation',
    'LTV',
    'Eri-TV',
    'Erisat',
    'Radio Television of Djibouti',
    'Horn Cable TV',
    'Sahal Cable TV',
    'Star Ocean Television',
    'Clouds TV',
    'ITV Tanzania',
    'Star TV Tanzania',
    'TBC',
    'East African Television',
    'EATV',
    'Wasafi TV',
    'NTV Uganda',
    'UBC',
    'NBS Television',
    'Bukedde TV',
    'Urban TV',
    'BBS Terefayina',
    'TV West',
    'TV East',
    'SEE TV',
    'Wan Luo TV',
    'SABC',
    'e.tv',
    'M-Net',
    'Newzroom Afrika',
    'eNCA',
    'SLBC',
    'Martin Plaut',
    'Horn Tribune',
    'Garowe Online',
    'Horseed Media',
    'AllAfrica',
    'The East African',
    'Ethiopian Herald',
    'New Vision',
    'The Monitor',
    'Daily Nation',
    'The Standard',
    'Business Daily',
    'Capital FM',
    'Radio France Internationale',
    'BBC Africa',
    'VOA Africa',
    'Deutsche Welle',
    'Al Jazeera English',
    'breaking news',
    'latest news',
    'current affairs',
    'politics',
    'elections',
    'government',
    'parliament',
    'president',
    'prime minister',
    'cabinet',
    'ministry',
    'opposition',
    'democracy',
    'governance',
    'policy',
    'legislation',
    'reform',
    'diplomacy',
    'foreign affairs',
    'international relations',
    'trade',
    'economy',
    'GDP',
    'inflation',
    'currency',
    'stock market',
    'banking',
    'development',
    'infrastructure',
    'transportation',
    'energy',
    'oil',
    'gas',
    'mining',
    'agriculture',
    'livestock',
    'crops',
    'farming',
    'food security',
    'drought',
    'famine',
    'climate change',
    'environment',
    'conservation',
    'wildlife',
    'tourism',
    'hotels',
    'airlines',
    'airports',
    'ports',
    'shipping',
    'manufacturing',
    'industry',
    'technology',
    'innovation',
    'digital',
    'internet',
    'mobile money',
    'fintech',
    'startups',
    'entrepreneurship',
    'employment',
    'unemployment',
    'jobs',
    'education',
    'universities',
    'schools',
    'students',
    'healthcare',
    'hospitals',
    'medical',
    'doctors',
    'health',
    'disease',
    'pandemic',
    'covid',
    'vaccines',
    'security',
    'military',
    'police',
    'terrorism',
    'conflict',
    'peace',
    'refugees',
    'humanitarian',
    'aid',
    'UN',
    'African Union',
    'IGAD',
    'EAC',
    'sports',
    'football',
    'athletics',
    'olympics',
    'culture',
    'music',
    'entertainment',
    'fashion',
    'lifestyle',
    'religion',
    'society',
    'community',
    'population',
    'census',
    'corruption',
    'transparency',
    'accountability',
    'human rights',
    'justice',
    'courts',
    'legal',
    'constitution',
    'poverty',
    'inequality',
    'urban',
    'rural',
    'migration',
    'diaspora',
    'remittances',
    'women',
    'youth',
    'children',
    'gender',
    'equality',
    'Horn of Africa',
    'East Africa',
    'sub-saharan Africa',
    'trending news',
    'live updates',
    'press release',
    'statement',
    'announcement',
    'report',
    'investigation',
    'exclusive',
    'interview',
    'analysis',
    'opinion',
    'editorial',
    'commentary',
    'debate',
    'crisis',
    'emergency',
    'disaster',
    'relief',
    'recovery',
    'reconstruction',
    'summit',
    'conference',
    'meeting',
    'agreement',
    'treaty',
    'sanctions',
    'embargo',
    'border',
    'customs',
    'visa',
    'passport',
    'citizenship',
    'immigration',
    'deportation',
    'asylum',
    'peacekeeping',
    'ceasefire',
    'negotiations',
    'mediation',
    'reconciliation',
    'stability',
    'instability',
    'unrest',
    'protests',
    'demonstrations',
    'strikes',
    'riots',
    'violence',
    'bloodshed',
    'casualties',
    'victims',
    'survivors',
    'witnesses',
    'investigation',
    'trial',
    'verdict',
    'sentence',
    'appeal',
    'bail',
    'arrest',
    'detention',
    'prison',
    'release',
    'pardon',
    'amnesty',
    'budget',
    'spending',
    'revenue',
    'taxes',
    'debt',
    'deficit',
    'surplus',
    'bonds',
    'loans',
    'grants',
    'funding',
    'investment',
    'project',
    'contract',
    'tender',
    'procurement',
    'audit',
    'fraud',
    'embezzlement',
    'bribery',
    'scandal',
    'misconduct',
    'investigation',
    'prosecution',
    'conviction',
    'acquittal',
    'compensation',
    'damages',
    'settlement',
    'lawsuit',
    'court case',
    'hearing',
    'testimony',
    'evidence',
    'witness',
    'jury',
    'judge',
    'lawyer',
    'attorney',
    'legal counsel',
    'defense',
    'prosecution',
    'plaintiff',
    'defendant',
    'civil rights',
    'freedom of speech',
    'press freedom',
    'media rights',
    'censorship',
    'journalism',
    'reporter',
    'correspondent',
    'editor',
    'publisher',
  ],
  generator: 'Next.js',
  applicationName: siteConfig.name,
  referrer: 'origin-when-cross-origin',
  authors: [{ name: 'Dawan Africa', url: siteConfig.url }],
  creator: 'Dawan Africa',
  publisher: 'Dawan Africa',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  manifest: '/manifest.json',
  alternates: {
    canonical: '/',
    types: {
      'application/rss+xml': '/rss.xml',
    },
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: siteConfig.name,
    description: siteConfig.description,
    images: [
      {
        url: '/og-default.png',
        width: 1200,
        height: 630,
        alt: `${siteConfig.name} - ${siteConfig.description}`,
        type: 'image/png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: siteConfig.name,
    description: siteConfig.description,
    images: ['/og-default.png'],
    creator: '@dawanafrica',
    site: '@dawanafrica',
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: '84QZctK6dL25aaWZQeIS4z04cFQTcKGTSnyZmMJzcvk',
  },
  category: 'news',
  classification: 'News Website',
  other: {
    'og:site_name': siteConfig.name,
    'application-name': siteConfig.name,
    'apple-mobile-web-app-title': siteConfig.name,
    'msapplication-TileColor': siteConfig.themeColor,
    'theme-color': siteConfig.themeColor,
  },
}

export default siteConfig
